// Safe typos: misspellings a human plausibly types (transpositions, doubled or
// dropped letters). These never change the meaning of the sentence.
const TYPOS = {
  "the": ["teh", "hte"],
  "this": ["thsi", "ths"],
  "and": ["adn"],
  "from": ["form"],
  "that": ["thta", "taht"],
  "with": ["wiht", "wth"],
  "have": ["hvae", "hve"],
  "about": ["abotu", "baout"],
  "because": ["becuase", "becase"],
  "think": ["thikn", "thnk"],
  "know": ["konw", "knwo"],
  "would": ["woudl", "woud"],
  "could": ["coudl", "coud"],
  "should": ["shoudl", "shoud"],
  "people": ["poeple", "peopel"],
  "things": ["thigns", "thngs"],
  "really": ["raelly", "realy"],
  "different": ["diferent", "diffrent"],
  "important": ["importnat", "importnt"],
  "please": ["pleae", "plase", "pleas"],
  "looking": ["looing", "lookng"],
  "thanks": ["thankss", "thanx"],
  "message": ["mesage", "messge"],
  "email": ["emial"],
  "sent": ["snet", "sentt"],
  "right": ["rigth", "rigt"],
  "might": ["migth", "migt"],
  "first": ["frist"],
  "around": ["arond", "aroud"],
  "always": ["allways", "alays"],
  "feedback": ["feedbak"],
  "meeting": ["meetig", "meetng"],
  "schedule": ["scedule", "scheudle"],
  "tomorrow": ["tommorow", "tommorrow"],
  "best": ["bst"],
  "need": ["nede", "ned"],
  "make": ["maek", "mkae"],
  "take": ["taek"],
  "time": ["tiem", "tmie"],
  "work": ["wirk", "wrok"],
  "start": ["strat"],
  "want": ["wat", "wnt"],
  "there": ["ther", "tehr"],
  "where": ["whre", "wher"],
  "hope": ["hop"],
  "sure": ["sur"],
  "next": ["nextt", "nxt"],
  "still": ["stil"],
  "well": ["wel"],
  "will": ["wil"],
  "let": ["lt"],
  "get": ["gt"],
  "much": ["muhc"],
  "more": ["mroe"],
  "very": ["vrey"],
  "even": ["evne"],
  "also": ["alsoo"],
  "just": ["jst"],
  "over": ["ovre"],
  "open": ["opne"],
  "done": ["doen", "dnoe"],
  "some": ["somee", "soem"],
  "been": ["ben"],
  "before": ["befoe", "beofre"],
  "after": ["afterr"],
  "during": ["durig", "durng"],
  "without": ["withou", "wihtout"],
  "include": ["inclue", "inclede"],
  "provide": ["provid", "porvide"],
  "receive": ["recieve", "recive"],
  "update": ["updat", "udpate"],
  "review": ["reveiw"],
  "confirm": ["conrim", "confrim"],
  "their": ["thier"],
  "your": ["yrou", "yuor"],
  "then": ["thn"],
  "hello": ["helloo", "helo"],
  "hi": ["hii", "ih"],
  "dear": ["daer"],
  "regards": ["regrads"],
  "cheers": ["cheerz", "chears"],
  "sincerely": ["sincerly"],
  "kind": ["kindd"],
  "thank": ["thnk"],
  "apologies": ["apolgogies"],
  "sorry": ["sory", "sorru"],
  "great": ["grat"],
  "welcome": ["welcom"],
  "forward": ["foward", "forwad"],
  "waiting": ["waitting"],
  "hear": ["haer"],
  "soon": ["sooon"],
  "today": ["todai"],
  "yesterday": ["yestarday"],
  "week": ["wek"],
  "month": ["mnoth"],
  "year": ["yaer"],
  "question": ["quesiton"],
  "questions": ["quesitons"],
  "problem": ["porblem"],
  "issue": ["isue"],
  "issues": ["isues"],
  "help": ["hlp"],
  "support": ["suport", "spport"],
  "team": ["tean"],
  "colleague": ["collegue"],
  "manager": ["manger"],
  "client": ["cleint"],
  "customer": ["custmer"],
  "project": ["projet"],
  "report": ["repoort"],
  "document": ["documet"],
  "attachment": ["atachment", "attachmnt"],
  "attached": ["atached"],
  "call": ["cal"],
  "talk": ["tlk"],
  "speak": ["spek"],
  "discuss": ["discus"],
  "discussion": ["discusion"],
  "agree": ["agre"],
  "agreed": ["agred"],
  "received": ["recived"],
  "checked": ["cheked"],
  "correct": ["corect"],
  "wrong": ["wrnog"],
  "happy": ["hapy"],
  "glad": ["gld"],
  "nice": ["nic"],
  "fine": ["fien"],
  "good": ["godo"],
  "better": ["beter"],
  "possible": ["posible"],
  "probably": ["probly"],
  "actually": ["actualy"],
  "basically": ["basicly"],
  "honestly": ["honstly"],
  "absolutely": ["absolutly"],
  "definitely": ["definitly"],
  "naturally": ["naturaly"],
  "usually": ["usally"],
  "normally": ["normaly"],
  "recently": ["recenty"],
  "currently": ["currenty"],
  "previous": ["previuos"],
  "example": ["exampel", "exmaple"],
  "information": ["infomation"],
  "details": ["detials"],
  "summary": ["sumary"],
  "deadline": ["dedline"],
  "budget": ["budjet"],
  "proposal": ["proposl", "porposal"],
  "proposals": ["proposls"],
  "suggestion": ["sugestion"],
  "recommend": ["recomend"],
  "recommendation": ["recomendation"],
  "available": ["avalable", "availble"],
  "interested": ["intrested", "intersted"],
  "opportunity": ["oppotunity", "oppertunity"]
};

// Homophone / near-word swaps. These pass spellcheck and CHANGE MEANING
// (their → there, accept → except), which reads as a grammar error rather
// than a typo. Off by default; enabled via the "Homophone swaps" popup toggle.
const HOMOPHONES = {
  "their": ["there"],
  "there": ["their"],
  "they're": ["their", "there"],
  "its": ["it's"],
  "it's": ["its"],
  "your": ["you're"],
  "you're": ["your"],
  "whose": ["who's"],
  "who's": ["whose"],
  "than": ["then"],
  "then": ["than"],
  "accept": ["except"],
  "except": ["accept"],
  "ensure": ["insure"],
  "insure": ["ensure"],
  "principle": ["principal"],
  "principal": ["principle"],
  "stationary": ["stationery"],
  "stationery": ["stationary"],
  "compliment": ["complement"],
  "complement": ["compliment"],
  "desert": ["dessert"],
  "dessert": ["desert"],
  "personal": ["personnel"],
  "personnel": ["personal"],
  "conscious": ["conscience"],
  "conscience": ["conscious"],
  "advice": ["advise"],
  "advise": ["advice"],
  "loose": ["lose"],
  "lose": ["loose"],
  "dear": ["deer"]
};
